sudo: required
language: java

jdk: openjdk8

env:
  global:
    - AUDIODEV=null
    - DISPLAY=:99.0

install:
 - git fetch --unshallow

addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
    packages:
      - libstdc++6
      - portaudio19-dev
      - libasound2-dev

services:
  - xvfb

before_install:
 - sudo apt-get install gnome-themes-standard
 - sudo apt-get install metacity
 - sudo apt-get install libwebkit-dev

cache:
  apt: true
  directories:
    - '$HOME/.m2/repository'

before_script:
 - metacity --sm-disable --replace &
 - sleep 10

script:
  - export
  - cd lionengine-editor-parent
  - mvn clean verify -U
